### ISSUE TITLE
Erreur "No results" de l'application M33 People

### ISSUE THREAD

**Issue by juliennassar** [theodo/m33-people#8]
Bug report : lorsqu'on se connecte avec Trello à l'application M33 People **avant** d'être invité au board Trello associé (https://github.com/theodo/m33-people), vous aurez une magnifique **Erreur 401** (cad compte Non Autorisé) visible dans la **console JS** de votre navigateur.
Si on vous y invite **après** au Trello en question, **l'erreur persiste**

du coup, quick fix avant que ce soit réellement résolu : ouvrez la console de votre navigateur, dans storage effacez le local storage (du coup le token d'authentification) et reconnectez vous.
BAM, ça remarche ;)

enfin presque... erreur à la première connexion -> https://github.com/theodo/m33-people/issues/7

**Comment by tcheymol** [comment]
@juliennassar Hello Julien, j'ai corrigé le problème. Est-ce que tu as moyen de tester si ça fonctionne ? Par exemple utiliser un nouveau compte Trello :) En attendant, je ferme l'Issue si c'est OK pour toi. Merci de ton retour
